schema_version = "1.0.0"

id = "gscatter"
version = "0.11.8"
name = "Gscatter"
tagline = "The free scattering tools made by Graswald"
maintainer = "Graswald GmbH <support@graswald3d.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://gscatter.com/"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["3D View", "Geometry Nodes"]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = ["SPDX:GPL-3.0-or-later"]
# Optional: required by some licenses.
copyright = ["2024 Graswald GmbH"]

# Optional list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "windows-arm64", "macos-x64", "macos-arm64", "linux-x64"]
# Other supported platforms: "windows-arm64", "macos-x64"

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
# wheels = [
#   "./wheels/t3dn_bip-1.0.9-py3-none-any.whl",
#   "./wheels/jsonschema-4.6.0-py3-none-any.whl",
#   "./wheels/attrs-21.4.0-py2.py3-none-any.whl",
#   "./wheels/pyrsistent-0.19.1-py3-none-any.whl",
#   "./wheels/mixpanel-4.9.0-py2.py3-none-any.whl",
#   "./wheels/six-1.16.0-py2.py3-none-any.whl",
#   "./wheels/sentry_sdk-1.5.4-py2.py3-none-any.whl",
#   "./wheels/pillow-10.4.0-cp311-cp311-macosx_10_10_x86_64.whl",
#   "./wheels/pillow-10.4.0-cp311-cp311-macosx_11_0_arm64.whl",
#   "./wheels/pillow-10.4.0-cp311-cp311-manylinux_2_28_x86_64.whl",
#   "./wheels/pillow-10.4.0-cp311-cp311-win_amd64.whl",
#   "./wheels/pillow-10.4.0-cp311-cp311-win_arm64.whl",
# ]
# Optional: Generate wheels manually
# pip wheel -r ./vendor/requirements.txt -w ./wheels --no-deps
# pip download pillow --dest ./wheels --only-binary=:all: --python-version=3.11 --platform=win_amd64
# pip download pillow --dest ./wheels --only-binary=:all: --python-version=3.11 --platform=win_arm64
# pip download pillow --dest ./wheels --only-binary=:all: --python-version=3.11 --platform=macosx_11_0_arm64
# pip download pillow --dest ./wheels --only-binary=:all: --python-version=3.11 --platform=macosx_10_15_x86_64
# pip download pillow --dest ./wheels --only-binary=:all: --python-version=3.11 --platform=manylinux_2_28_x86_64


# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.

[permissions]
network = "Updates, Downloads, Anonymous Tracking"
files = "Install/Load/Save Graswald Assets, Presets, Node-Groups"

# Optional: build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.vscode/",
  "/vendors/",
  "/testing/",
  ".*",
  "*.zip",
  "*.blend[0-9]",
  "build.py",
  "exclude.txt",
  "README.md",
  "latest_versions.json",
  "backend/",
  "update/",
  "migration/",
  "updater/graswald_updater/.*",
  "updater/graswald_updater/.github/",
  "updater/graswald_updater/README.md",
  "updater/graswald_updater/example_implementation.py",
  "updater/graswald_updater/requirements_aws.txt",
  "updater/graswald_updater/requirements_http.txt",
]
